### ISSUE TITLE
Unchecking SHOW_ON_START results in blank graph

### ISSUE THREAD

**Issue by shbach** [agerardin/joplin-plugin-knowledge-graph#14]
In the latest version of the plugin, [the fix for the panel persisting](https://github.com/agerardin/joplin-plugin-knowledge-graph/issues/12) breaks the graph. Now with the `SHOW_ON_START` unchecked, the graph is blank:
![image](https://user-images.githubusercontent.com/5298745/149675824-e6326a98-a062-4140-813c-4cfd0400e7c3.png)

**Comment by agerardin** [comment]
I cannot reproduce this.
Can you confirm it is still an issue and if so
check Help > Toggle development tools and copy any error message that pops up?
Also does this happen at startup or after exiting the settings?

**Comment by shbach** [comment]
For me it happens if SHOW_ON_START is unchecked and then upon restarting Joplin the graph is blank.

This is the only error message I saw that mentioned this plugin directly:
![image](https://user-images.githubusercontent.com/5298745/149705941-625282cd-90dd-4f33-8bf7-29983b91b95c.png)

**Comment by agerardin** [comment]
It seems that Joplin is trying to update its layout and fails to do so.
The user preferences for the layout may be corrupted.
I would guess that uninstalling and reinstalling the graph plugin should fix the problem, as it will probably re-register.

Failing code from  Joplin :
```
		case 'MAIN_LAYOUT_SET_ITEM_PROP':

			{
				let newLayout = produce(state.mainLayout, (draftLayout: LayoutItem) => {
					iterateItems(draftLayout, (_itemIndex: number, item: LayoutItem, _parent: LayoutItem) => {
						if (item.key === action.itemKey) {
							(item as any)[action.propName] = action.propValue;
							return false;
						}
						return true;
					});
				});
```

**Comment by shbach** [comment]
Uninstalling and reinstalling the plugin fixed it! I'll close this issue.
