### ISSUE TITLE
Highlight for Current Note

### ISSUE THREAD

**Issue by rubbsdecvik** [agerardin/joplin-plugin-knowledge-graph#4]
This plugin is amazing for visualizing the relationships between notes. I know that the graph will center on the selected note, but it would be great if there was a nice visual queue for what note is currently selected in the editor. This would be especially helpful if you have scroll and/or panned around to explore the map.

**Comment by agerardin** [comment]
I am glad you find it useful! All notes currently selected in the editor should appear highlighted in the graph. For a note without any links, it simply appears as a slim blue circle around the node so it may be hard to notice. Or are you referring to something else?

**Comment by rubbsdecvik** [comment]
Sorry for the delay in response. I did not notice the highlighted circle around the selected note. Now that I see that, I believe that works for my use case. I will close this issue.
