### ISSUE TITLE
Visible all window/frame

### ISSUE THREAD

**Issue by gssantana** [agerardin/joplin-plugin-knowledge-graph#8]
First of all, thanks for your great job!!

Is there possibility when we use the button show the graph, it fills all text editor area size with a custom shortcut?

![image](https://user-images.githubusercontent.com/57970850/147518881-773bccfa-95cb-4332-baaf-927434735ba6.png)

**Comment by agerardin** [comment]
Thanks! As far as I know this kind of behavior is not currently supported by the Joplin window system.

**Comment by shbach** [comment]
If you resize the editor panel to be as small as possible while the graph panel is showing, later when you toggle the graph on, it will take up most of the editor space you indicated, though it's not 100%. The note tab and the top of the editor panel with the title will still show but I think that's pretty usuable amount of space.

**Comment by agerardin** [comment]
The new release should fix the resizing issue.

<img width="1276" alt="Screen Shot 2021-12-31 at 10 02 51 AM" src="https://user-images.githubusercontent.com/2278749/147829595-89f44501-e909-4a78-b168-e85957acb67d.png">

Having a plugin panel going fullscreen is not supported at this time so I will close this issue.
