### ISSUE TITLE
Links with anchor won't take effect

### ISSUE THREAD

**Issue by LintaoAmons** [agerardin/joplin-plugin-knowledge-graph#9]
````
3. Some description
	- [Parameter expansion forms#string-chopping](:/65fad2c360454e0aac06eb576f6be6e1#string-chopping) <1>
	- [Parameter expansion forms](:/65fad2c360454e0aac06eb576f6be6e1) <2>
```

When I link a note with an anchor, shown as `<1>`, the graph won't recognize this as a link.
Only when I add `<2>` this line, the graph generate the connection between two notes.

**Comment by agerardin** [comment]
Correct, linking to section of a note is not yet supported but it should (and it will!)
I was not sure it was actually supported by Joplin, I may have tried a while ago but I cannot remember if I succeeded.
How do you create them at the first place?

**Comment by shbach** [comment]
@agerardin The [Note link system plugin](https://github.com/ylc395/joplin-plugin-note-link-system) provides the easiest way of doing it. Another one is the [copy anchor link plugin](https://github.com/hieuthi/joplin-plugin-copy-anchor-link). I've been using links with anchors a lot more often now so having this supported is a must for me.

**Comment by LintaoAmons** [comment]
There's a plugin named `Note Link System`.

When I input `@@` it will show a popup window to let fuzzy find notes to link and select.

After selecting a note to link, It shows the anchors to select.

- AS shown in the picture
    - ![image](https://user-images.githubusercontent.com/95092244/147806382-8dbc50a0-fc8b-4c33-a0d9-b91b66bbe2af.png)

**Comment by agerardin** [comment]
Excellent! I have tried the note link system and it does an excellent job to simplify linking note sections. I will push a version with a fix soon.

**Comment by agerardin** [comment]
Hello! the new release (v1.0.5) will now properly pick up link with elementId. Thanks for pointing this out.

**Comment by shbach** [comment]
Seems to be working for me. This issue can probably be closed.
